import Link from "next/link";

export const metadata = {
  title: "Terms of Service — ApplyFaster",
};

export default function Terms() {
  return (
    <main className="min-h-screen pt-24 pb-16 px-4 sm:px-6 lg:px-8">
      <div className="max-w-3xl mx-auto">
        <Link
          href="/"
          className="text-sm text-indigo-400 hover:text-indigo-300 transition mb-8 inline-block"
        >
          ← Back to ApplyFaster
        </Link>
        <h1 className="text-3xl font-bold mb-8">Terms of Service</h1>
        <div className="prose prose-invert prose-sm max-w-none space-y-6 text-gray-300">
          <p>
            <strong>Last updated:</strong> March 16, 2026
          </p>

          <h2 className="text-xl font-semibold text-white mt-8">
            The service
          </h2>
          <p>
            ApplyFaster generates cover letters using AI based on the resume
            and job description you provide. The generated content is a
            starting point — you should review, edit, and personalize every
            letter before sending it.
          </p>

          <h2 className="text-xl font-semibold text-white mt-8">
            Your responsibility
          </h2>
          <p>
            You are responsible for the accuracy of the information you
            provide and the final content of any cover letter you send to
            employers. ApplyFaster does not guarantee job interviews,
            employment, or specific outcomes.
          </p>

          <h2 className="text-xl font-semibold text-white mt-8">
            What you own
          </h2>
          <p>
            You own the cover letters generated by ApplyFaster. We claim no
            ownership or license over your generated content. Use it however
            you want.
          </p>

          <h2 className="text-xl font-semibold text-white mt-8">
            Payments and refunds
          </h2>
          <p>
            Free tier: one cover letter, no payment required. Paid plans are
            billed through Stripe. Pro subscriptions can be cancelled at any
            time. We offer refunds on a case-by-case basis — email us if
            you&apos;re not satisfied.
          </p>

          <h2 className="text-xl font-semibold text-white mt-8">
            Fair use
          </h2>
          <p>
            Don&apos;t abuse the service (automated scraping, generating
            content for resale, overwhelming our servers). We reserve the
            right to limit or terminate accounts that violate fair use.
          </p>

          <h2 className="text-xl font-semibold text-white mt-8">
            Changes
          </h2>
          <p>
            We may update these terms. Continued use of the service after
            changes means you accept the updated terms.
          </p>

          <h2 className="text-xl font-semibold text-white mt-8">
            Contact
          </h2>
          <p>
            Questions? Email{" "}
            <a
              href="mailto:support@applyfaster.ai"
              className="text-indigo-400 hover:text-indigo-300"
            >
              support@applyfaster.ai
            </a>
          </p>
        </div>
      </div>
    </main>
  );
}
